import { useEffect, useMemo, useState } from 'react';
import { Check, FileUp, Pencil, Plus, Search, Settings2, Trash2, Upload } from '@/lib/remixIconShim';
import { Badge, Button, Card, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, Input, Textarea } from '../ui';
import { cn } from '../../lib/utils';

type LibraryEntry = { id: string; name: string; category: string; prompt: string; updatedAt: number };
const STORAGE_KEY = 'design-work-quick-notes';
const LIBRARY_KEY = 'design-work-prompt-library';
const categories = ['我的', '精选', '职业', '商业', '工具', '语言', '办公', '通用', '写作', '编程', '情感', '教育', '创意', '学术', '设计', '艺术', '娱乐', '生活', '医疗', '游戏'];
const defaults: LibraryEntry[] = [
  { id: 'entry-brief', name: '打工牛马小助手', category: '我的', prompt: '你是我日常处理工作的助手，我在遇到问题时，需要根据具体需求帮助我解决问题。', updatedAt: Date.now() - 840000 },
  { id: 'entry-comfy', name: 'ComfyUI 报错小助手', category: '我的', prompt: '你是一个专注于处理 ComfyUI AI 绘画报错的技术人员，熟练掌握各种编码技术。', updatedAt: Date.now() - 1680000 },
  { id: 'entry-video', name: '视频内容分析专家', category: '精选', prompt: '专业的视频内容分析专家，具备深度解构和结构化分析视频内容的能力。', updatedAt: Date.now() - 2700000 },
  { id: 'entry-qwen', name: 'Qwen-image 文生图提示词', category: '精选', prompt: '专注生成 QWEN-IMAGE 模型提示词的助手，基于用户创意扩写结构化提示词。', updatedAt: Date.now() - 3120000 },
  { id: 'entry-wan', name: 'Wan2.1 图生视频提示词', category: '视频', prompt: '将静态图像转化动态视频内容，生成适合 Wan2.1 的结构化提示词。', updatedAt: Date.now() - 4200000 },
  { id: 'entry-flux', name: 'Flux 文生图提示词', category: '设计', prompt: '你来充当一位有艺术气息的 FLUX prompt 助理，根据自然语言想象完整画面。', updatedAt: Date.now() - 5700000 },
  { id: 'entry-writing', name: '短篇科幻小说作家', category: '写作', prompt: '结合科学知识和哲学思考，创作具有独特世界观与情绪张力的短篇科幻小说。', updatedAt: Date.now() - 7200000 },
  { id: 'entry-ui', name: 'UI/UX 设计师专家', category: '设计', prompt: '在视觉设计与用户体验领域提供专业建议，关注可用性、层次和一致性。', updatedAt: Date.now() - 9600000 },
];
const readEntries = (): LibraryEntry[] => { try { const saved = JSON.parse(localStorage.getItem(LIBRARY_KEY) || 'null'); if (Array.isArray(saved)) return saved; const old = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); if (Array.isArray(old) && old.length) return old.map((note: { id: string; content: string; tags?: string[]; updatedAt: number }) => ({ id: note.id, name: note.content.trim().split('\n')[0] || '未命名词条', category: note.tags?.[0] || '我的', prompt: note.content, updatedAt: note.updatedAt })); } catch { /* use defaults */ } return defaults; };
const formatDate = (value: number) => new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit' }).format(value);

export const QuickNotes = ({ query = '' }: { query?: string }) => {
  const [entries, setEntries] = useState<LibraryEntry[]>(readEntries);
  const [category, setCategory] = useState('全部'); const [manageMode, setManageMode] = useState(false); const [selected, setSelected] = useState<string[]>([]);
  const [editorOpen, setEditorOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null);
  const [draft, setDraft] = useState({ name: '', category: '我的', prompt: '' }); const [importUrl, setImportUrl] = useState('');
  useEffect(() => { localStorage.setItem(LIBRARY_KEY, JSON.stringify(entries)); }, [entries]);
  const counts = useMemo(() => new Map(categories.map((item) => [item, entries.filter((entry) => entry.category === item).length])), [entries]);
  const filtered = useMemo(() => entries.filter((entry) => { const inCategory = category === '全部' || entry.category === category; return inCategory && `${entry.name} ${entry.prompt} ${entry.category}`.toLowerCase().includes(query.trim().toLowerCase()); }), [entries, category, query]);
  const openCreate = () => { setEditingId(null); setDraft({ name: '', category: '我的', prompt: '' }); setEditorOpen(true); };
  const openEdit = (entry: LibraryEntry) => { setEditingId(entry.id); setDraft({ name: entry.name, category: entry.category, prompt: entry.prompt }); setEditorOpen(true); };
  const saveEntry = () => { if (!draft.name.trim() || !draft.prompt.trim()) return; const next = { name: draft.name.trim(), category: draft.category, prompt: draft.prompt.trim(), updatedAt: Date.now() }; setEntries((current) => editingId ? current.map((entry) => entry.id === editingId ? { ...entry, ...next } : entry) : [{ id: `entry-${Date.now()}`, ...next }, ...current]); setEditorOpen(false); };
  const remove = (id: string) => setEntries((current) => current.filter((entry) => entry.id !== id)); const toggleSelected = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const selectAll = () => setSelected(selected.length === filtered.length ? [] : filtered.map((entry) => entry.id)); const deleteSelected = () => { setEntries((current) => current.filter((entry) => !selected.includes(entry.id))); setSelected([]); setManageMode(false); };
  const importEntry = () => { if (!importUrl.trim()) return; setEntries((current) => [{ id: `entry-${Date.now()}`, name: '外部导入词条', category: '我的', prompt: importUrl.trim(), updatedAt: Date.now() }, ...current]); setImportUrl(''); setImportOpen(false); };

  return <main className="ui-module-panel flex h-full min-h-0">
    <aside className="ui-module-divider-r hidden w-[200px] shrink-0 overflow-y-auto bg-sidebar px-[12px] py-3 text-sidebar-foreground md:block"><div className="mb-2 flex h-12 items-center px-2 text-xs font-semibold text-sidebar-foreground/70">助手库</div><div className="space-y-0.5">{['全部', ...categories].map((item) => { const count = item === '全部' ? entries.length : counts.get(item) || 0; const isActive = category === item; return <button key={item} type="button" onClick={() => setCategory(item)} className={cn('flex h-8 w-full items-center justify-between rounded-md px-2 text-xs transition-colors', isActive ? 'border-[var(--surface-panel-border-width)] border-[var(--action-secondary-border)] bg-[var(--action-secondary-bg)] text-[var(--action-secondary-foreground)] hover:bg-[var(--action-secondary-bg-hover)] hover:text-[var(--action-secondary-foreground)]' : 'text-sidebar-foreground/70 hover:bg-sidebar-accent hover:text-sidebar-accent-foreground')}><span>{item}</span><span className="tabular-nums opacity-70">{count}</span></button>; })}</div></aside>
    <section className="min-w-0 flex-1 overflow-y-auto bg-background"><header className="ui-module-divider-b sticky top-0 z-10 flex h-12 shrink-0 flex-wrap items-center gap-2 bg-background/95 px-4 backdrop-blur"><div className="flex min-w-0 flex-1 items-center gap-2"><h1 className="text-sm font-semibold">{category === '全部' ? '助手库' : category}</h1><span className="text-xs text-muted-foreground">{filtered.length}</span></div><Button type="button" variant="ghost" size="sm" onClick={() => setImportOpen(true)} className="h-8 gap-1.5 text-xs"><Upload size={20} /> 从外部导入</Button><Button type="button" variant={manageMode ? 'secondary' : 'ghost'} size="sm" onClick={() => { setManageMode((value) => !value); setSelected([]); }} className="h-8 gap-1.5 text-xs"><Settings2 size={20} /> 管理助手</Button><Button type="button" variant="ghost" size="sm" onClick={openCreate} className="h-8 gap-1.5 text-xs"><Plus size={20} /> 创建助手</Button></header>
      {manageMode && <div className="ui-module-divider-b flex h-10 items-center gap-3 px-4 text-xs"><Button type="button" variant="ghost" size="sm" onClick={selectAll} className="h-7 gap-1.5 px-2"><Check size={16} /> 全选</Button><span className="text-muted-foreground">已选择 {selected.length}</span><Button type="button" variant="ghost" size="sm" disabled={!selected.length} onClick={deleteSelected} className="ml-auto h-7 gap-1.5 px-2 text-destructive"><Trash2 size={16} /> 删除</Button></div>}
      <div className="grid grid-cols-1 gap-3 p-4 lg:grid-cols-2 xl:grid-cols-3">{filtered.map((entry) => <Card key={entry.id} padding="none" className={cn('group relative min-h-[150px] overflow-hidden', selected.includes(entry.id) && 'ring-2 ring-ring/30')}><button type="button" className="block w-full text-left" onClick={() => manageMode ? toggleSelected(entry.id) : openEdit(entry)}>{manageMode && <span className={cn('absolute right-3 top-3 grid h-5 w-5 place-items-center rounded border', selected.includes(entry.id) ? 'border-primary bg-primary text-primary-foreground' : 'border-muted-foreground/40')} aria-hidden="true">{selected.includes(entry.id) && <Check size={12} />}</span>}<div className="p-4"><div className="flex items-start justify-between gap-2"><h2 className="min-w-0 truncate text-sm font-semibold">{entry.name}</h2><span className="shrink-0 text-[10px] text-muted-foreground">{formatDate(entry.updatedAt)}</span></div><Badge variant="subtle" className="mt-2 text-[10px]">{entry.category}</Badge><p className="mt-3 line-clamp-4 text-xs leading-5 text-muted-foreground">{entry.prompt}</p></div></button>{!manageMode && <div className="absolute bottom-2 right-2 flex opacity-0 transition-opacity group-hover:opacity-100"><Button type="button" variant="ghost" size="iconSm" onClick={() => openEdit(entry)} aria-label={`编辑 ${entry.name}`} title="编辑" className="h-7 w-7"><Pencil size={16} /></Button><Button type="button" variant="ghost" size="sm" onClick={() => remove(entry.id)} aria-label={`删除 ${entry.name}`} title="删除" className="h-7 w-7 text-muted-foreground hover:text-destructive"><Trash2 size={16} /></Button></div>}</Card>)}{!filtered.length && <div className="col-span-full flex min-h-60 flex-col items-center justify-center text-center text-xs text-muted-foreground"><Search size={20} /><p className="mt-3">没有匹配的词条</p><Button type="button" variant="ghost" size="sm" onClick={openCreate} className="mt-2 h-8">创建一个助手</Button></div>}</div>
    </section>
    <Dialog open={editorOpen} onOpenChange={setEditorOpen}><DialogContent className="max-w-[520px] gap-0 p-0"><DialogHeader className="border-b border-border px-5 py-4 pr-14"><DialogTitle className="text-base">{editingId ? '编辑助手' : '创建助手'}</DialogTitle><DialogDescription className="text-xs">保存一条可重复使用的提示词到词库。</DialogDescription></DialogHeader><div className="space-y-4 px-5 py-4"><label className="block text-xs font-medium">名称<Input autoFocus value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="输入名称" className="mt-2 h-8 text-xs" /></label><label className="block text-xs font-medium">提示词<Textarea value={draft.prompt} onChange={(event) => setDraft({ ...draft, prompt: event.target.value })} placeholder="输入提示词" className="mt-2 min-h-[150px] text-xs leading-6" /></label><label className="block text-xs font-medium">分类<select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} className="mt-2 h-8 w-full rounded-md border-0 bg-muted px-2 text-xs outline-none">{categories.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="flex justify-end gap-2 border-t border-border px-5 py-3"><Button type="button" variant="ghost" size="sm" onClick={() => setEditorOpen(false)}>取消</Button><Button type="button" variant="primary" size="sm" onClick={saveEntry} disabled={!draft.name.trim() || !draft.prompt.trim()}>{editingId ? '保存更改' : '添加到词库'}</Button></div></DialogContent></Dialog>
    <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="max-w-[440px] gap-0 p-0"><DialogHeader className="border-b border-border px-5 py-4 pr-14"><DialogTitle className="text-base">从外部导入</DialogTitle><DialogDescription className="text-xs">通过 URL 或文件内容添加词条。</DialogDescription></DialogHeader><div className="space-y-3 px-5 py-4"><div className="flex gap-2"><Button type="button" variant="secondary" size="sm" className="h-8 gap-1.5"><Upload size={16} /> URL</Button><Button type="button" variant="ghost" size="sm" className="h-8 gap-1.5"><FileUp size={16} /> 文件</Button></div><Input value={importUrl} onChange={(event) => setImportUrl(event.target.value)} placeholder="输入 JSON URL" className="h-8 text-xs" /></div><div className="flex justify-end gap-2 border-t border-border px-5 py-3"><Button type="button" variant="ghost" size="sm" onClick={() => setImportOpen(false)}>取消</Button><Button type="button" variant="primary" size="sm" onClick={importEntry} disabled={!importUrl.trim()}>导入</Button></div></DialogContent></Dialog>
  </main>;
};
