import { useEffect, useState } from 'react';
import { CheckCircle2, Globe2, Pencil, Plus, RefreshCw, Trash2 } from '@/lib/remixIconShim';
import { Button } from '../../ui/Button';
import { Input } from '../../ui/Input';
import { Switch } from '../../ui/Switch';

type Source = { id: string; name: string; manifestUrl: string; homepageUrl: string | null; enabled: boolean; lastSuccessAt: number | null; itemCount: number; errorMessage: string | null };
type CatalogSource = { id: string; name: string; homepageUrl: string | null; itemCount: number };
const call = async (url: string, init?: RequestInit) => { const response = await fetch(url, init); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || '操作失败'); return data; };
export function PromptSourcesSettings() {
  const [items, setItems] = useState<Source[]>([]); const [catalogSources, setCatalogSources] = useState<CatalogSource[]>([]); const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [editingId, setEditingId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = async () => { const [data, cases] = await Promise.all([call('/api/prompt-sources'), call('/api/cases')]); setItems(Array.isArray(data.items) ? data.items : []); setCatalogSources(Array.isArray(cases.sources) ? cases.sources : []); };
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  const add = async () => { setBusy(true); setError(''); try { await call('/api/prompt-sources', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, manifestUrl: url }) }); setName(''); setUrl(''); await load(); setMessage('来源已添加'); } catch (e) { setError(e instanceof Error ? e.message : '添加失败'); } finally { setBusy(false); } };
  const update = async (source: Source, patch: Partial<Source>) => { try { await call(`/api/prompt-sources/${source.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : '更新失败'); } };
  const beginEdit = (source: Source) => { setEditingId(source.id); setName(source.name); setUrl(source.manifestUrl); setError(''); };
  const saveEdit = async () => { if (!editingId || !name.trim() || !url.trim()) return; setBusy(true); setError(''); try { await call(`/api/prompt-sources/${editingId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: name.trim(), manifestUrl: url.trim() }) }); setEditingId(null); setName(''); setUrl(''); await load(); setMessage('来源已更新'); } catch (e) { setError(e instanceof Error ? e.message : '更新失败'); } finally { setBusy(false); } };
  const sync = async (id?: string) => { setBusy(true); setError(''); try { await call(id ? `/api/prompt-sources/${id}/sync` : '/api/prompt-sources/sync', { method: 'POST' }); await load(); setMessage('同步完成'); } catch (e) { setError(e instanceof Error ? e.message : '同步失败'); } finally { setBusy(false); } };
  return <div className="space-y-5"><div className="flex items-center justify-between"><div><h4 className="flex items-center gap-2 text-sm font-semibold"><Globe2 size={16} />公开案例来源</h4><p className="mt-1 text-xs text-muted-foreground">管理 Manifest 同步入口，并查看其中声明的真实来源网站。案例页不会直接请求第三方网站。</p></div><Button size="sm" variant="secondary" onClick={() => void sync()} disabled={busy}><RefreshCw size={14} />同步全部</Button></div>
    <div className="rounded-[var(--surface-panel-radius)] border border-border bg-card p-4"><div className="mb-3 text-xs font-medium text-muted-foreground">Manifest 同步入口</div><div className="grid gap-2 md:grid-cols-[180px_1fr_auto]"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="入口名称" className="h-9 text-xs" /><Input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://example.com/manifest.json" className="h-9 text-xs" /><Button size="sm" variant="secondary" onClick={() => void add()} disabled={busy || !name.trim() || !url.trim()}><Plus size={14} />添加入口</Button></div></div>
    <div className="divide-y divide-border rounded-[var(--surface-panel-radius)] border border-border bg-card">{items.length ? items.map((source) => editingId === source.id ? <div key={source.id} className="grid gap-2 p-4 md:grid-cols-[180px_1fr_auto_auto]"><Input value={name} onChange={(e) => setName(e.target.value)} aria-label="入口名称" className="h-9 text-xs" /><Input value={url} onChange={(e) => setUrl(e.target.value)} aria-label="Manifest URL" className="h-9 text-xs" /><Button size="sm" variant="secondary" onClick={() => void saveEdit()} disabled={busy || !name.trim() || !url.trim()}>保存</Button><Button size="sm" variant="ghost" onClick={() => { setEditingId(null); setName(''); setUrl(''); }}>取消</Button></div> : <div key={source.id} className="flex items-center gap-3 p-4"><Switch checked={source.enabled} onCheckedChange={(checked) => void update(source, { enabled: checked })} /><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-sm font-medium"><span>{source.name}</span><span className="text-xs text-muted-foreground">{source.itemCount} 条</span></div><p className="truncate text-xs text-muted-foreground">{source.manifestUrl}</p>{source.errorMessage ? <p className="mt-1 text-xs text-destructive">{source.errorMessage}</p> : source.lastSuccessAt ? <p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CheckCircle2 size={12} />最近同步 {new Date(source.lastSuccessAt).toLocaleString('zh-CN')}</p> : null}</div><Button size="sm" variant="ghost" onClick={() => beginEdit(source)} disabled={busy} aria-label={`编辑${source.name}`}><Pencil size={14} /></Button><Button size="sm" variant="ghost" onClick={() => void sync(source.id)} disabled={busy} aria-label={`同步${source.name}`}><RefreshCw size={14} /></Button><Button size="sm" variant="ghost" onClick={() => { if (window.confirm(`删除来源「${source.name}」？`)) void call(`/api/prompt-sources/${source.id}`, { method: 'DELETE' }).then(load).catch((e) => setError(e.message)); }} aria-label={`删除${source.name}`}><Trash2 size={14} /></Button></div>) : <div className="p-6 text-center text-xs text-muted-foreground">还没有配置公开来源</div>}</div>
    <section className="rounded-[var(--surface-panel-radius)] border border-border bg-card p-4"><div className="mb-3 flex items-center justify-between"><div><h5 className="text-sm font-semibold">已发现的来源网站</h5><p className="mt-1 text-xs text-muted-foreground">这些网站来自已同步 Manifest 的 sources 声明，案例卡片会显示对应来源。</p></div><span className="text-xs text-muted-foreground">{catalogSources.length} 个网站</span></div>{catalogSources.length ? <div className="grid gap-2 md:grid-cols-2">{catalogSources.map((catalogSource) => <a key={catalogSource.id} href={catalogSource.homepageUrl || undefined} target="_blank" rel="noreferrer" className="flex min-w-0 items-center gap-3 rounded-md bg-muted/40 px-3 py-2.5 transition-colors hover:bg-[var(--surface-hover)]"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-md bg-background text-muted-foreground"><Globe2 size={14} /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium text-foreground">{catalogSource.name}</span><span className="block truncate text-[11px] text-muted-foreground">{catalogSource.homepageUrl || '未提供主页链接'}</span></span><span className="shrink-0 text-[11px] text-muted-foreground">{catalogSource.itemCount} 条</span></a>)}</div> : <div className="py-5 text-center text-xs text-muted-foreground">同步后会显示 Manifest 中声明的来源网站</div>}</section>{(message || error) && <p className={`text-xs ${error ? 'text-destructive' : 'text-muted-foreground'}`}>{error || message}</p>}</div>;
}
